//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.8.2'.
//
package values.banque.type.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.NullableDoubleAdapter
import com.apollographql.apollo3.api.NullableStringAdapter
import com.apollographql.apollo3.api.Optional
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.nullable
import com.apollographql.apollo3.api.present
import kotlin.IllegalStateException
import kotlin.Unit
import ma.ensa.banque.type.CompteRequest

public object CompteRequest_InputAdapter : Adapter<CompteRequest> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      CompteRequest = throw IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: CompteRequest,
  ): Unit {
    if (value.solde is Optional.Present) {
      writer.name("solde")
      NullableDoubleAdapter.present().toJson(writer, customScalarAdapters, value.solde)
    }
    if (value.dateCreation is Optional.Present) {
      writer.name("dateCreation")
      NullableStringAdapter.present().toJson(writer, customScalarAdapters, value.dateCreation)
    }
    if (value.type is Optional.Present) {
      writer.name("type")
      TypeCompte_ResponseAdapter.nullable().present().toJson(writer, customScalarAdapters,
          value.type)
    }
  }
}
