//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.8.2'.
//
package values.banque.type

import com.apollographql.apollo3.api.Optional
import kotlin.Double
import kotlin.String

public data class CompteRequest(
  public val solde: Optional<Double?> = Optional.Absent,
  public val dateCreation: Optional<String?> = Optional.Absent,
  public val type: Optional<TypeCompte?> = Optional.Absent,
)
