//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.8.2'.
//
package values.banque.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.NullableStringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.nullable
import com.apollographql.apollo3.api.obj
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import values.banque.DeleteCompteMutation

public object DeleteCompteMutation_ResponseAdapter {
  public object Data : Adapter<_root_ide_package_.values.banque.DeleteCompteMutation.Data> {
    public val RESPONSE_NAMES: List<String> = listOf("deleteCompte")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        _root_ide_package_.values.banque.DeleteCompteMutation.Data {
      var _deleteCompte: _root_ide_package_.values.banque.DeleteCompteMutation.DeleteCompte? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> _deleteCompte = DeleteCompte.obj().nullable().fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return _root_ide_package_.values.banque.DeleteCompteMutation.Data(
        deleteCompte = _deleteCompte
      )
    }

    public override fun toJson(
        writer: JsonWriter,
        customScalarAdapters: CustomScalarAdapters,
        `value`: _root_ide_package_.values.banque.DeleteCompteMutation.Data,
    ): Unit {
      writer.name("deleteCompte")
      DeleteCompte.obj().nullable().toJson(writer, customScalarAdapters, value.deleteCompte)
    }
  }

  public object DeleteCompte : Adapter<_root_ide_package_.values.banque.DeleteCompteMutation.DeleteCompte> {
    public val RESPONSE_NAMES: List<String> = listOf("id")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        _root_ide_package_.values.banque.DeleteCompteMutation.DeleteCompte {
      var _id: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> _id = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return _root_ide_package_.values.banque.DeleteCompteMutation.DeleteCompte(
        id = _id
      )
    }

    public override fun toJson(
        writer: JsonWriter,
        customScalarAdapters: CustomScalarAdapters,
        `value`: _root_ide_package_.values.banque.DeleteCompteMutation.DeleteCompte,
    ): Unit {
      writer.name("id")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.id)
    }
  }
}
