//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.8.2'.
//
package values.banque.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import kotlin.IllegalStateException
import kotlin.Unit
import ma.ensa.banque.SaveCompteMutation
import ma.ensa.banque.type.adapter.CompteRequest_InputAdapter

public object SaveCompteMutation_VariablesAdapter : Adapter<SaveCompteMutation> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      SaveCompteMutation = throw IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: SaveCompteMutation,
  ): Unit {
    writer.name("compte")
    CompteRequest_InputAdapter.obj().toJson(writer, customScalarAdapters, value.compte)
  }
}
