//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.8.2'.
//
package values.banque

import com.apollographql.apollo3.annotations.ApolloAdaptableWith
import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.ObjectAdapter
import com.apollographql.apollo3.api.Query
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import kotlin.Any
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import ma.ensa.banque.adapter.GetAllComptesQuery_ResponseAdapter
import ma.ensa.banque.selections.GetAllComptesQuerySelections
import ma.ensa.banque.type.TypeCompte

public class GetAllComptesQuery() : Query<GetAllComptesQuery.Data> {
  public override fun equals(other: Any?): Boolean = other != null && other::class == this::class

  public override fun hashCode(): Int = this::class.hashCode()

  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    // This operation doesn't have any variable
  }

  public override fun adapter(): Adapter<Data> = GetAllComptesQuery_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = ma.ensa.banque.type.Query.type
  )
  .selections(selections = GetAllComptesQuerySelections.__root)
  .build()

  @ApolloAdaptableWith(GetAllComptesQuery_ResponseAdapter.Data::class)
  public data class Data(
    public val allComptes: List<AllCompte?>?,
  ) : Query.Data

  public data class AllCompte(
    public val id: String?,
    public val solde: Double?,
    public val dateCreation: String?,
    public val type: TypeCompte?,
  )

  public companion object {
    public const val OPERATION_ID: String =
        "85b7f7a35b95ddf45df80aceb52fa4ea4e65348b7f1cd1beccb3ec215570deb7"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * query GetAllComptes {
     *   allComptes {
     *     id
     *     solde
     *     dateCreation
     *     type
     *   }
     * }
     */
    public val OPERATION_DOCUMENT: String
      get() = "query GetAllComptes { allComptes { id solde dateCreation type } }"

    public const val OPERATION_NAME: String = "GetAllComptes"
  }
}
